//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mongo.Migration.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mongo.Migration.Resources.Exceptions.ErrorTexts", typeof(ErrorTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MongoMigration was already initialized.
        /// </summary>
        public static string AlreadyInitialized {
            get {
                return ResourceManager.GetString("AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application directory could not be found.
        /// </summary>
        public static string AppDirNotFound {
            get {
                return ResourceManager.GetString("AppDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database could not be found for: &apos;{0}&apos;, database: &apos;{1}&apos;.
        /// </summary>
        public static string ConnectionCheckError {
            get {
                return ResourceManager.GetString("ConnectionCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration &apos;{0}&apos; contains duplicate version: {1}.
        /// </summary>
        public static string DuplicateVersion {
            get {
                return ResourceManager.GetString("DuplicateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value: {0}.
        /// </summary>
        public static string InvalidVersionValue {
            get {
                return ResourceManager.GetString("InvalidVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MongoClient, you need to register a MongoClient to the DI-Container or define connection settings with MongoMigrationSettings.
        /// </summary>
        public static string NoMongoClient {
            get {
                return ResourceManager.GetString("NoMongoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions must have format: major.minor.revision, this doesn&apos;t match: {0}.
        /// </summary>
        public static string VersionStringToLong {
            get {
                return ResourceManager.GetString("VersionStringToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentVersion: &apos;{0}&apos;, DocumentVersion: &apos;{1}&apos;, LatestMigrationVersion: &apos;{2}&apos;.
        /// </summary>
        public static string VersionViolated {
            get {
                return ResourceManager.GetString("VersionViolated", resourceCulture);
            }
        }
    }
}
